2025-08-22 11:53:22,671 - __main__ - INFO - Broadcasting to channel -1002332120603 (1/60)
2025-08-22 11:53:22,673 - __main__ - INFO - Sending text message to -1002332120603
2025-08-22 11:53:23,472 - __main__ - INFO - Scheduling auto delete for -1002332120603 in 1 minutes
2025-08-22 11:53:23,476 - __main__ - INFO - Broadcasting to channel -1002494891280 (2/60)
2025-08-22 11:53:24,488 - __main__ - INFO - Sending text message to -1002494891280
2025-08-22 11:53:25,472 - __main__ - INFO - Scheduling auto delete for -1002494891280 in 1 minutes
2025-08-22 11:53:25,476 - __main__ - INFO - Broadcasting to channel -1002434419924 (3/60)
2025-08-22 11:53:26,488 - __main__ - INFO - Sending text message to -1002434419924
2025-08-22 11:53:27,206 - __main__ - INFO - Scheduling auto delete for -1002434419924 in 1 minutes
2025-08-22 11:53:27,222 - __main__ - INFO - Broadcasting to channel -1002331523047 (4/60)
2025-08-22 11:53:28,233 - __main__ - INFO - Sending text message to -1002331523047
2025-08-22 11:53:28,875 - __main__ - INFO - Scheduling auto delete for -1002331523047 in 1 minutes
2025-08-22 11:53:28,878 - __main__ - INFO - Broadcasting to channel -1002299930478 (5/60)
2025-08-22 11:53:29,890 - __main__ - INFO - Sending text message to -1002299930478
2025-08-22 11:53:30,546 - __main__ - INFO - Scheduling auto delete for -1002299930478 in 1 minutes
2025-08-22 11:53:30,982 - __main__ - INFO - Broadcasting to channel -1002598444604 (6/60)
2025-08-22 11:53:31,984 - __main__ - INFO - Sending text message to -1002598444604
2025-08-22 11:53:32,592 - __main__ - INFO - Scheduling auto delete for -1002598444604 in 1 minutes
2025-08-22 11:53:32,595 - __main__ - INFO - Broadcasting to channel -1002551731587 (7/60)
2025-08-22 11:53:33,606 - __main__ - INFO - Sending text message to -1002551731587
2025-08-22 11:53:34,263 - __main__ - INFO - Scheduling auto delete for -1002551731587 in 1 minutes
2025-08-22 11:53:34,266 - __main__ - INFO - Broadcasting to channel -1002561719909 (8/60)
2025-08-22 11:53:35,280 - __main__ - INFO - Sending text message to -1002561719909
2025-08-22 11:53:35,975 - __main__ - INFO - Scheduling auto delete for -1002561719909 in 1 minutes
2025-08-22 11:53:35,978 - __main__ - INFO - Broadcasting to channel -1002186328901 (9/60)
2025-08-22 11:53:36,990 - __main__ - INFO - Sending text message to -1002186328901
2025-08-22 11:53:37,694 - __main__ - INFO - Scheduling auto delete for -1002186328901 in 1 minutes
2025-08-22 11:53:37,697 - __main__ - INFO - Broadcasting to channel -1002151853140 (10/60)
2025-08-22 11:53:38,708 - __main__ - INFO - Sending text message to -1002151853140
2025-08-22 11:53:39,358 - __main__ - INFO - Scheduling auto delete for -1002151853140 in 1 minutes
2025-08-22 11:53:39,794 - __main__ - INFO - Broadcasting to channel -1002649033400 (11/60)
2025-08-22 11:53:40,796 - __main__ - INFO - Sending text message to -1002649033400
2025-08-22 11:53:41,696 - __main__ - INFO - Scheduling auto delete for -1002649033400 in 1 minutes
2025-08-22 11:53:41,698 - __main__ - INFO - Broadcasting to channel -1002652369756 (12/60)
2025-08-22 11:53:42,710 - __main__ - INFO - Sending text message to -1002652369756
2025-08-22 11:53:43,485 - __main__ - INFO - Scheduling auto delete for -1002652369756 in 1 minutes
2025-08-22 11:53:43,488 - __main__ - INFO - Broadcasting to channel -1002687831932 (13/60)
2025-08-22 11:53:44,499 - __main__ - INFO - Sending text message to -1002687831932
2025-08-22 11:53:45,515 - __main__ - INFO - Scheduling auto delete for -1002687831932 in 1 minutes
2025-08-22 11:53:45,518 - __main__ - INFO - Broadcasting to channel -1002513351060 (14/60)
2025-08-22 11:53:46,529 - __main__ - INFO - Sending text message to -1002513351060
2025-08-22 11:53:47,204 - __main__ - INFO - Scheduling auto delete for -1002513351060 in 1 minutes
2025-08-22 11:53:47,207 - __main__ - INFO - Broadcasting to channel -1002640670406 (15/60)
2025-08-22 11:53:48,218 - __main__ - INFO - Sending text message to -1002640670406
2025-08-22 11:53:48,893 - __main__ - INFO - Scheduling auto delete for -1002640670406 in 1 minutes
2025-08-22 11:53:49,292 - __main__ - INFO - Broadcasting to channel -1002676133760 (16/60)
2025-08-22 11:53:50,293 - __main__ - INFO - Sending text message to -1002676133760
2025-08-22 11:53:51,022 - __main__ - INFO - Scheduling auto delete for -1002676133760 in 1 minutes
2025-08-22 11:53:51,024 - __main__ - INFO - Broadcasting to channel -1002638134670 (17/60)
2025-08-22 11:53:52,028 - __main__ - INFO - Sending text message to -1002638134670
2025-08-22 11:53:52,715 - __main__ - INFO - Scheduling auto delete for -1002638134670 in 1 minutes
2025-08-22 11:53:52,718 - __main__ - INFO - Broadcasting to channel -1002615827803 (18/60)
2025-08-22 11:53:53,731 - __main__ - INFO - Sending text message to -1002615827803
2025-08-22 11:53:54,393 - __main__ - INFO - Scheduling auto delete for -1002615827803 in 1 minutes
2025-08-22 11:53:54,396 - __main__ - INFO - Broadcasting to channel -1002312328124 (19/60)
2025-08-22 11:53:55,409 - __main__ - INFO - Sending text message to -1002312328124
2025-08-22 11:53:56,029 - __main__ - INFO - Scheduling auto delete for -1002312328124 in 1 minutes
2025-08-22 11:53:56,032 - __main__ - INFO - Broadcasting to channel -1002597993561 (20/60)
2025-08-22 11:53:57,044 - __main__ - INFO - Sending text message to -1002597993561
2025-08-22 11:53:57,824 - __main__ - INFO - Scheduling auto delete for -1002597993561 in 1 minutes
2025-08-22 11:53:58,312 - __main__ - INFO - Broadcasting to channel -1002276881717 (21/60)
2025-08-22 11:53:59,314 - __main__ - INFO - Sending text message to -1002276881717
2025-08-22 11:53:59,934 - __main__ - INFO - Scheduling auto delete for -1002276881717 in 1 minutes
2025-08-22 11:53:59,937 - __main__ - INFO - Broadcasting to channel -1002590167742 (22/60)
2025-08-22 11:54:00,951 - __main__ - INFO - Sending text message to -1002590167742
2025-08-22 11:54:01,610 - __main__ - INFO - Scheduling auto delete for -1002590167742 in 1 minutes
2025-08-22 11:54:01,613 - __main__ - INFO - Broadcasting to channel -1002574475404 (23/60)
2025-08-22 11:54:02,627 - __main__ - INFO - Sending text message to -1002574475404
2025-08-22 11:54:03,693 - __main__ - INFO - Scheduling auto delete for -1002574475404 in 1 minutes
2025-08-22 11:54:03,695 - __main__ - INFO - Broadcasting to channel -1002600145250 (24/60)
2025-08-22 11:54:04,704 - __main__ - INFO - Sending text message to -1002600145250
2025-08-22 11:54:05,414 - __main__ - INFO - Scheduling auto delete for -1002600145250 in 1 minutes
2025-08-22 11:54:05,417 - __main__ - INFO - Broadcasting to channel -1002634728097 (25/60)
2025-08-22 11:54:06,429 - __main__ - INFO - Sending text message to -1002634728097
2025-08-22 11:54:08,035 - __main__ - INFO - Scheduling auto delete for -1002634728097 in 1 minutes
2025-08-22 11:54:08,466 - __main__ - INFO - Broadcasting to channel -1002589342159 (26/60)
2025-08-22 11:54:09,468 - __main__ - INFO - Sending text message to -1002589342159
2025-08-22 11:54:10,163 - __main__ - INFO - Scheduling auto delete for -1002589342159 in 1 minutes
2025-08-22 11:54:10,166 - __main__ - INFO - Broadcasting to channel -1002565250647 (27/60)
2025-08-22 11:54:11,175 - __main__ - INFO - Sending text message to -1002565250647
2025-08-22 11:54:11,803 - __main__ - INFO - Scheduling auto delete for -1002565250647 in 1 minutes
2025-08-22 11:54:11,806 - __main__ - INFO - Broadcasting to channel -1002666332012 (28/60)
2025-08-22 11:54:12,817 - __main__ - INFO - Sending text message to -1002666332012
2025-08-22 11:54:13,486 - __main__ - INFO - Scheduling auto delete for -1002666332012 in 1 minutes
2025-08-22 11:54:13,489 - __main__ - INFO - Broadcasting to channel -1002389966907 (29/60)
2025-08-22 11:54:14,500 - __main__ - INFO - Sending text message to -1002389966907
2025-08-22 11:54:15,130 - __main__ - INFO - Scheduling auto delete for -1002389966907 in 1 minutes
2025-08-22 11:54:15,133 - __main__ - INFO - Broadcasting to channel -1002831751557 (30/60)
2025-08-22 11:54:16,144 - __main__ - INFO - Sending text message to -1002831751557
2025-08-22 11:54:16,855 - __main__ - INFO - Scheduling auto delete for -1002831751557 in 1 minutes
2025-08-22 11:54:17,282 - __main__ - INFO - Broadcasting to channel -1002722014587 (31/60)
2025-08-22 11:54:18,283 - __main__ - INFO - Sending text message to -1002722014587
2025-08-22 11:54:19,255 - __main__ - INFO - Scheduling auto delete for -1002722014587 in 1 minutes
2025-08-22 11:54:19,258 - __main__ - INFO - Broadcasting to channel -1002840220443 (32/60)
2025-08-22 11:54:20,269 - __main__ - INFO - Sending text message to -1002840220443
2025-08-22 11:54:21,246 - __main__ - INFO - Scheduling auto delete for -1002840220443 in 1 minutes
2025-08-22 11:54:21,249 - __main__ - INFO - Broadcasting to channel -1002653015406 (33/60)
2025-08-22 11:54:22,261 - __main__ - INFO - Sending text message to -1002653015406
2025-08-22 11:54:23,557 - __main__ - INFO - Scheduling auto delete for -1002653015406 in 1 minutes
2025-08-22 11:54:23,566 - __main__ - INFO - Broadcasting to channel -1002531976616 (34/60)
2025-08-22 11:54:24,582 - __main__ - INFO - Sending text message to -1002531976616
2025-08-22 11:54:25,183 - __main__ - INFO - Scheduling auto delete for -1002531976616 in 1 minutes
2025-08-22 11:54:25,185 - __main__ - INFO - Broadcasting to channel -1002637865617 (35/60)
2025-08-22 11:54:26,197 - __main__ - INFO - Sending text message to -1002637865617
2025-08-22 11:54:26,894 - __main__ - INFO - Scheduling auto delete for -1002637865617 in 1 minutes
2025-08-22 11:54:27,350 - __main__ - INFO - Broadcasting to channel -1002685771446 (36/60)
2025-08-22 11:54:28,351 - __main__ - INFO - Sending text message to -1002685771446
2025-08-22 11:54:28,972 - __main__ - INFO - Scheduling auto delete for -1002685771446 in 1 minutes
2025-08-22 11:54:28,973 - __main__ - INFO - Broadcasting to channel -1002349903210 (37/60)
2025-08-22 11:54:29,979 - __main__ - INFO - Sending text message to -1002349903210
2025-08-22 11:54:30,694 - __main__ - INFO - Scheduling auto delete for -1002349903210 in 1 minutes
2025-08-22 11:54:30,697 - __main__ - INFO - Broadcasting to channel -1002350893763 (38/60)
2025-08-22 11:54:31,707 - __main__ - INFO - Sending text message to -1002350893763
2025-08-22 11:54:32,705 - __main__ - INFO - Scheduling auto delete for -1002350893763 in 1 minutes
2025-08-22 11:54:32,707 - __main__ - INFO - Broadcasting to channel -1002707811738 (39/60)
2025-08-22 11:54:33,718 - __main__ - INFO - Sending text message to -1002707811738
2025-08-22 11:54:34,814 - __main__ - INFO - Scheduling auto delete for -1002707811738 in 1 minutes
2025-08-22 11:54:34,816 - __main__ - INFO - Broadcasting to channel -1002397054467 (40/60)
2025-08-22 11:54:35,821 - __main__ - INFO - Sending text message to -1002397054467
2025-08-22 11:54:36,414 - __main__ - INFO - Scheduling auto delete for -1002397054467 in 1 minutes
2025-08-22 11:54:36,816 - __main__ - INFO - Broadcasting to channel -1002891628298 (41/60)
2025-08-22 11:54:37,817 - __main__ - INFO - Sending text message to -1002891628298
2025-08-22 11:54:38,435 - __main__ - INFO - Scheduling auto delete for -1002891628298 in 1 minutes
2025-08-22 11:54:38,437 - __main__ - INFO - Broadcasting to channel -1002648254511 (42/60)
2025-08-22 11:54:39,443 - __main__ - INFO - Sending text message to -1002648254511
2025-08-22 11:54:40,043 - __main__ - INFO - Scheduling auto delete for -1002648254511 in 1 minutes
2025-08-22 11:54:40,046 - __main__ - INFO - Broadcasting to channel -1002504532501 (43/60)
2025-08-22 11:54:41,055 - __main__ - INFO - Sending text message to -1002504532501
2025-08-22 11:54:42,063 - __main__ - INFO - Scheduling auto delete for -1002504532501 in 1 minutes
2025-08-22 11:54:42,065 - __main__ - INFO - Broadcasting to channel -1002870892494 (44/60)
2025-08-22 11:54:43,074 - __main__ - INFO - Sending text message to -1002870892494
2025-08-22 11:54:44,030 - __main__ - INFO - Scheduling auto delete for -1002870892494 in 1 minutes
2025-08-22 11:54:44,033 - __main__ - INFO - Broadcasting to channel -1002750339239 (45/60)
2025-08-22 11:54:45,043 - __main__ - INFO - Sending text message to -1002750339239
2025-08-22 11:54:45,894 - __main__ - INFO - Scheduling auto delete for -1002750339239 in 1 minutes
2025-08-22 11:54:46,290 - __main__ - INFO - Broadcasting to channel -1002534442908 (46/60)
2025-08-22 11:54:47,296 - __main__ - INFO - Sending text message to -1002534442908
2025-08-22 11:54:48,264 - __main__ - INFO - Scheduling auto delete for -1002534442908 in 1 minutes
2025-08-22 11:54:48,267 - __main__ - INFO - Broadcasting to channel -1002657241590 (47/60)
2025-08-22 11:54:49,279 - __main__ - INFO - Sending text message to -1002657241590
2025-08-22 11:54:50,276 - __main__ - INFO - Scheduling auto delete for -1002657241590 in 1 minutes
2025-08-22 11:54:50,278 - __main__ - INFO - Broadcasting to channel -1002364006834 (48/60)
2025-08-22 11:54:51,288 - __main__ - INFO - Sending text message to -1002364006834
2025-08-22 11:54:51,936 - __main__ - INFO - Scheduling auto delete for -1002364006834 in 1 minutes
2025-08-22 11:54:51,939 - __main__ - INFO - Broadcasting to channel -1002772338577 (49/60)
2025-08-22 11:54:52,950 - __main__ - INFO - Sending text message to -1002772338577
2025-08-22 11:54:53,582 - __main__ - INFO - Scheduling auto delete for -1002772338577 in 1 minutes
2025-08-22 11:54:53,583 - __main__ - INFO - Broadcasting to channel -1002839156778 (50/60)
2025-08-22 11:54:54,589 - __main__ - INFO - Sending text message to -1002839156778
2025-08-22 11:54:55,255 - __main__ - INFO - Scheduling auto delete for -1002839156778 in 1 minutes
2025-08-22 11:54:55,667 - __main__ - INFO - Broadcasting to channel -1002172600666 (51/60)
2025-08-22 11:54:56,668 - __main__ - INFO - Sending text message to -1002172600666
2025-08-22 11:54:57,284 - __main__ - INFO - Scheduling auto delete for -1002172600666 in 1 minutes
2025-08-22 11:54:57,286 - __main__ - INFO - Broadcasting to channel -1002816912603 (52/60)
2025-08-22 11:54:58,292 - __main__ - INFO - Sending text message to -1002816912603
2025-08-22 11:54:58,972 - __main__ - INFO - Scheduling auto delete for -1002816912603 in 1 minutes
2025-08-22 11:54:58,974 - __main__ - INFO - Broadcasting to channel -1002871252351 (53/60)
2025-08-22 11:54:59,979 - __main__ - INFO - Sending text message to -1002871252351
2025-08-22 11:55:00,488 - __main__ - ERROR - Exception details: ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: CHAT_RESTRICTED
2025-08-22 11:55:00,489 - __main__ - INFO - Broadcasting to channel -1002717124881 (54/60)
2025-08-22 11:55:01,490 - __main__ - INFO - Sending text message to -1002717124881
2025-08-22 11:55:02,672 - __main__ - INFO - Scheduling auto delete for -1002717124881 in 1 minutes
2025-08-22 11:55:02,674 - __main__ - INFO - Broadcasting to channel -1002809729666 (55/60)
2025-08-22 11:55:03,681 - __main__ - INFO - Sending text message to -1002809729666
2025-08-22 11:55:04,301 - __main__ - INFO - Scheduling auto delete for -1002809729666 in 1 minutes
2025-08-22 11:55:04,833 - __main__ - INFO - Broadcasting to channel -1002771863248 (56/60)
2025-08-22 11:55:05,854 - __main__ - INFO - Sending text message to -1002771863248
2025-08-22 11:55:06,507 - __main__ - INFO - Scheduling auto delete for -1002771863248 in 1 minutes
2025-08-22 11:55:06,547 - __main__ - INFO - Broadcasting to channel -1002204507609 (57/60)
2025-08-22 11:55:07,833 - __main__ - INFO - Sending text message to -1002204507609
2025-08-22 11:55:09,313 - __main__ - INFO - Scheduling auto delete for -1002204507609 in 1 minutes
2025-08-22 11:55:09,316 - __main__ - INFO - Broadcasting to channel -1002431437495 (58/60)
2025-08-22 11:55:10,326 - __main__ - INFO - Sending text message to -1002431437495
2025-08-22 11:55:10,954 - __main__ - INFO - Scheduling auto delete for -1002431437495 in 1 minutes
2025-08-22 11:55:10,957 - __main__ - INFO - Broadcasting to channel -1002203225057 (59/60)
2025-08-22 11:55:11,969 - __main__ - INFO - Sending text message to -1002203225057
2025-08-22 11:55:12,622 - __main__ - INFO - Scheduling auto delete for -1002203225057 in 1 minutes
2025-08-22 11:55:12,623 - __main__ - INFO - Broadcasting to channel -1002070181214 (60/60)
2025-08-22 11:55:13,630 - __main__ - INFO - Sending text message to -1002070181214
2025-08-22 11:55:14,350 - __main__ - INFO - Scheduling auto delete for -1002070181214 in 1 minutes
2025-08-22 12:03:55,427 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:03:55,433 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:03:58,901 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:03:58,906 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:03:59,363 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:03:59,367 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:03,111 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:03,124 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:03,839 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:03,864 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:08,099 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:08,111 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:09,403 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:09,413 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:14,647 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:14,658 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:16,872 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:16,877 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:21,094 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:21,100 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:25,313 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:25,323 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:33,554 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:33,565 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:41,773 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:41,784 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:04:58,003 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:04:58,007 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:05:01,474 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:05:01,485 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:05:33,941 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:05:33,954 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

2025-08-22 12:05:37,787 - TeleBot - ERROR - Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-08-22 12:05:37,798 - TeleBot - ERROR - Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 1234, in __threaded_polling
    polling_thread.raise_exceptions()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 112, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\util.py", line 94, in run
    task(*args, **kwargs)
    ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 688, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
                               allowed_updates=allowed_updates,
                               timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\__init__.py", line 660, in get_updates
    json_updates = apihelper.get_updates(
        self.token, offset=offset, limit=limit, timeout=timeout, allowed_updates=allowed_updates,
        long_polling_timeout=long_polling_timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 332, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 168, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\telebot\apihelper.py", line 195, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

